workflows:
  build_dia_register_release:
    name: Build DIA Register (Optimized)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ZIP_FILE: "dia_register_fixed.zip"
        UNZIP_DIR: "project_unzipped"

    scripts:
      # 1️⃣ Unzip your uploaded Flutter project
      - name: Extract project
        script: |
          echo "📦 Extracting Flutter project..."
          rm -rf $UNZIP_DIR
          unzip -q "$ZIP_FILE" -d "$UNZIP_DIR"
          cd "$UNZIP_DIR"
          echo "✅ Extraction complete. Current directory:"
          pwd
          ls -la

      # 2️⃣ Install dependencies
      - name: Install Flutter dependencies
        script: |
          echo "🚀 Running flutter pub get..."
          flutter pub get

      # 3️⃣ Build optimized release APK
      - name: Build Android APK (optimized)
        script: |
          echo "🏗️ Building optimized DIA Register release..."
          flutter build apk --release \
            --split-per-abi \
            --obfuscate \
            --split-debug-info=build/debug_info
          echo "✅ Build complete."

      # 4️⃣ Move all generated APKs to output folder
      - name: Move APKs to output
        script: |
          echo "📂 Moving built APKs..."
          mkdir -p ../build_outputs
          cp build/app/outputs/flutter-apk/*.apk ../build_outputs/
          echo "✅ APKs ready in build_outputs directory."

    artifacts:
      - build_outputs/*.apk

    publishing:
      email:
        recipients:
          - your@email.com
